# Generated by Django 5.0.7 on 2024-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
